### ISSUE TITLE
Biom file with metadata won't upload

### ISSUE THREAD

**Issue by christinez** [PitchInteractiveInc/Phinch#46]
Hi there, I have tried to upload my biom file with the metadata included (as you instructed) and it won't upload. The upload bar moves from the left to the right but nothing happens afterwards.

Biom file is output from QIIME.

**Comment by hollybik** [comment]
Two things to try:

First, make sure you are using the correct BIOIM format (Phinch only works with BIOM file type 1.0, the JSON-formatted file that is produced from QIIME version 1.8. The new BIOM files from QIIME 1.9 are in HDF5 format, and will NOT work in Phinch - you will need to convert this to the JSON file formatted BIOM file).

If your BIOM file is JSON formatted and still not working, then can you try the suggestions in this thread (converting back to classic OTU table and then back to BIOM with metadata re-added): https://groups.google.com/forum/#!topic/phinch/rsIk8DCQ0VM

Let me know if either of these suggestions work for you. If not, them please provide more specifics about the BIOM file version and how you generated your file.

**Comment by christinez** [comment]
Ok, so I didn't have my biom file in JSON format, so I converted and added metadata and it still didn't work.

So, next I worked through the thread that you posted and converted back to classic OTU table and back to BIOM, and that didn't work either.

**Comment by hollybik** [comment]
You're going to have to be a bit more specific if you want further help troubleshooting - it is very difficult to figure out what's wrong based on the vague information you've relayed so far.

-Are you using Phinch in Google Chrome? Chrome is currently the only browser supported.
-What type of data are you working with? OTU tables from rRNA amplicons? 16S/18S/ITS?
-What version of QIIME are you using?
-What is the specific error you're encountering from Phinch after trying to convert?
-Do you have both taxonomy AND metadata embedded in your BIOM file?

Can you also send me the header from your JSON-formatted BIOM file so I can get some more information, e.g. just copy and paste the part that looks like this:

{"id": "None","format": "Biological Observation Matrix 1.0.0","format_url": "http://biom-format.org","type": "OTU table","generated_by": "BIOM-Format 1.1.2","date": "2014-03-21T11:37:16.138764","matrix_type": "sparse","matrix_element_type": "float","shape": [67900, 95],"data":

**Comment by christinez** [comment]
Sorry I was so vague.

I am using Phinch in Google Chrome. I am working with OTU tables from 16S rRNA amplicons. I did my otu picking using UPARSE and assigned taxonomy and converted to BIOM in QIIME 1.9. I made sure to make a JSON BIOM file.

The BIOM file has taxonomy and I use the command you have listed in your help section to embed the metadata file.

I'm not receiving any error from PHINCH. I browse for my file and click upload. It looks like a bar goes across the upload area but then nothing happens. It just says on the upload screen.

when I look at the header of my JSON BIOM file, it looks like a mess of ?? and other symbols. I do not see the header that you have posted.

Perhaps this is the issue. This BIOM file has worked fine in QIIME. Is there a particular way I can reformat this to work in Phinch.



?????????????????`??
 xTREE????????????????`HEAPX ?observationsample8??
                                                  id
                                                   `
                                                   type `
                                                        H
                                                        format-ur`
                                                                 P
                                                                  format-versi@n
generated-b`                                                                   H
           creation-dat`
                       H
                        sha@?
                             0
                             n@???TREE????????????????hHEAPXmatrixidsmetadatagroup-metadata GCOL
                                                                                                No Table ID	OTU tablehttp://biom-format.orgBIOM-Format 2.1.32015-03-20T11:32:38.900173133814675	642
379
   1152
73412510553691203988445122696552180961225793454771139952 163!1180"1476#84$608%1339&267'747(930)1501*439+248,215-1497.322/7370211167223383147747395179616927582813429226:981;1566<1446=75>1084?637@168A567B148C300D261E424F562G756H1462I223J49K1639L1185M814N657O1469P177Q1336R499S254T229U1332V78W514X1465Y435Z676[1184\308]306^108_431`1527a568b208c295d572e751f386g644h743i231j1436k425l1208m354n838o345p444q592r310s736t787u1468v1219w341x1473y948z1337{1282|507}1479~112201?1499?1498?334?1092?1503?560?294?288?1097?1502?645?729?245?1470?1662?356?135?388?170?166?413?34?1685?1341?357?721?1656?490?362?1137?153?1544?1432?324?132?275?648?80?500?1287SNO?????о????REE?????????????????&HEAPX dataindicesindptr8SNOD(??0???????????? @4
                                                                                 4?
                                                                                  deflat?=
                                                                                          UPTRE?????????????????8(??/???6??

**Comment by hollybik** [comment]
Your BIOM file is not in JSON format, so it hasn't been converted correctly. The header you posted if from a BIOM 2.1 file (indicated in bold below, from the 7th line of the header you posted)

ID OTU tablehttp://biom-format.org**BIOM-Format 2.1.3**2015-03-20T11:32:38.900173133814675 642 379 1152

The scripts for converting BIOM files in between formats are here (you'll need to use the biom convert command in QIIME): http://biom-format.org/documentation/biom_conversion.html

Your correctly formatted JSON file (BIOM format 1.0) will be a plain text file. The file should be formatted like these examples when you open it in a text editor: http://biom-format.org/documentation/format_versions/biom-1.0.html

**Comment by christinez** [comment]
Ok, so there must be some sort of glitch with QIIME 1.9. No matter what I did, the biom file would not convert to JSON. And I tried the link you provided as well as scouring the web for other information regarding this.

I eventually just converted to BIOM on another computer that had an older version of QIIME and it converted perfectly and I was able to upload to Phinch.

Thank you for all of your help and suggestions. I wonder if anyone else if having this problem on QIIME 1.9?

**Comment by hollybik** [comment]
Great, glad you got it to work! I haven't heard anyone else having specific issues with QIIME 1.9, but the release is quite new and I'm sure many people are still switching over.

**Comment by Aqleem12** [comment]
Dear Dr. Hollybik,

I convert featuretable.biom from QIIME2. I than convert it into jason, and upload, into MetaCoNet, two days gone, still did not get any output. What is the issue? It took so much time.

Thanks
Aqleem Abbas

**Comment by hollybik** [comment]
Hi Aqleem,

You need to make sure your feature table includes your sample metadata (QIIME mapping file) and taxonomy. Here's good thread with some troubleshooting suggestions: https://github.com/PitchInteractiveInc/Phinch/issues/46

We don't have any control over the Phinch installation within MetaComet, so please troubleshoot your files on our own Phinch web interface at http://phinch.org

**Comment by Aqleem12** [comment]
Dear Sir,

The feature table of qiime 2 has :top row contains sample name, first
column contain OTUs and within these OTUs counts per sample. Will it work ?
It take much more time than but did not finish. I will follow your
suggestions and let you  know

Thanks
 Aqleem Abbas
