### ISSUE TITLE
Trouble with Uploading to Phinch

### ISSUE THREAD

**Issue by kmgallagher** [PitchInteractiveInc/Phinch#55]
I am using chrome, and qiime 190
I converted my biom file to a json file successfully (I think). When I click load the file, does load the file but I get the black loading circle . The circle never goes away and I never get to visualize my data even though it appears to have accepted my format.
Here is the header that I have:
{"id": "None","format": "Biological Observation Matrix 2.1.0","format_url": "http://biom-format.org","matrix_type": "sparse","generated_by": "BIOM-Format 2.1.3","date": "2016-04-06T12:21:52.378948","type": "OTU table","matrix_element_type": "float","shape": [2307, 3],"data":
Thanks,
KG

**Comment by hollybik** [comment]
Your BIOM file is in the wrong format (v2.0) - it needs to be converted to v1.0. Phinch does not support BIOM 2.0 files or higher (HDF5 format, the new default output format for QIIME 1.9 and higher); these files MUST be converted to JSON-formatted BIOM 1.0 files before they can be loaded into Phinch.

See the Quick Start Guide: https://github.com/PitchInteractiveInc/Phinch/wiki/Quick-Start or troubleshoot/convert according to this thread: https://github.com/PitchInteractiveInc/Phinch/issues/46
