### ISSUE TITLE
Unable to import dense biom files

### ISSUE THREAD

**Issue by iimog** [PitchInteractiveInc/Phinch#64]
The github page of phinch states:
> Phinch supports both "sparse" and "dense" BIOM formats (although sparse .biom files are highly recommended, since the file size is much smaller).

However trying to load a dense biom file leads to a strange filter page and no visualizations at all.
Try this simple dense file from the biom-format.org website:
https://gist.github.com/iimog/0f81cde695e26a5c8146fb306399c9f7

Looking at the code I see that many operations are hard coded for sparse data. So dense tables have to either be converted to sparse by Phinch, or all those operations have to be changed.

Else it might also be ok to state that Phinch can only handle sparse data.

**Comment by hollybik** [comment]
Thanks for pointing this out - I wasn't previously aware that we had hardcoded "sparse" format into the current release of Phinch. I have now updated the wiki documentation to reflect this limitation.
