### ISSUE TITLE
Issue uploading a test file to Phinch.org 

### ISSUE THREAD

**Issue by status-five** [PitchInteractiveInc/Phinch#82]
Hello, 

I was looking at Phinch.org and thought I'd upload a test file, Phinch.org does not upload the file correctly and I get the spiny Phinch.org dots of death when I do so. 

I've tested the file for correct format:
```
 $ biom validate-table  -i test.tx.biom 

The input file is a valid BIOM-formatted file.
```

I've tried:

- Google Chrome is up to date
-- Version 62.0.3202.94 (Official Build) (64-bit)

- Chromium
-- Version 62.0.3171.0 (Developer Build) (64-bit)
 
- Firefox
-- 57.0 (64-bit)

All on Mac OSX 10.13.1

Aforementioned biom here: [test.tx.biom.txt](https://github.com/PitchInteractiveInc/Phinch/files/1488387/test.tx.biom.txt) Although I had to add a .txt on the end to get it to upload.

**Comment by status-five** [comment]
Should also mention file was generated with Mothur version=1.39.5

**Comment by nthitz** [comment]
Looking at your test file I think this is related to https://github.com/PitchInteractiveInc/Phinch/issues/81 . It looks like your columns have null metadata which currently breaks our tool. You could convert all instances of `"metadata": null` to `"metadata": []` and things should work better. In the future this won't be needed but for now it is.

**Comment by status-five** [comment]
That's seems to have done it. Looks like it's working now. 
 Seeing as #81 already talks about this, I'll close this ticket out. 
Thank you.
